name: gccsnapshot_test

on: [workflow_call, pull_request]

env:
  MYSQL_DATABASE: 'ragnarok'
  MYSQL_USER: 'ragnarok'
  MYSQL_PASSWORD: 'ragnarok'
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  DEBIAN_COMMON_PACKAGES: make zlib1g-dev libpcre3-dev git python2 libzstd-dev gcc gcc-snapshot

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CC: [gcc]
        RENEWAL: ["", "--disable-renewal"]
        CLIENT_TYPE: ["", "--enable-packetver-re", "--enable-packetver-zero"]
        SANITIZER: ["--disable-manager", "--disable-manager --enable-sanitize=full"]
        PACKET_VERSION: ["--enable-packetver=20220518", "--enable-packetver=20130724"]
        exclude:
          - PACKET_VERSION: "--enable-packetver=20130724"
            CLIENT_TYPE: "--enable-packetver-zero"
    container:
      image: debian:unstable
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 33306:3306
        env:
          MYSQL_DATABASE: 'ragnarok'
          MYSQL_USER: 'ragnarok'
          MYSQL_PASSWORD: 'ragnarok'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    env:
      INSTALL_PACKAGES: ${{ matrix.CC }} mariadb-client libmariadbclient-dev-compat
      SQLHOST: mariadb
      CC: ${{ matrix.CC }}
      CONFIGURE_FLAGS: CC=${{ matrix.CC }} --enable-debug --enable-Werror --enable-buildbot ${{ matrix.RENEWAL }} ${{ matrix.CLIENT_TYPE }} ${{ matrix.SANITIZER }} ${{ matrix.PACKET_VERSION }} --enable-lto
      PACKET_VERSION: ${{ matrix.PACKET_VERSION }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: info
        run: |
          uname -a

      - name: install packages
        run: |
          ./tools/ci/retry.sh apt-get update
          ./tools/ci/retry.sh apt-get install -y -qq $INSTALL_PACKAGES $DEBIAN_COMMON_PACKAGES

      - name: gcc version
        run: |
          export PATH=/usr/lib/gcc-snapshot/bin:$PATH
          gcc --version
          ls -la /usr/lib/x86_64-linux-gnu/libasan.* || true
          ls -la /usr/lib/gcc-snapshot/lib/libasan.* || true
          ls -la /usr/lib/gcc-snapshot/lib/libasan.so.8.0.0

      - name: init database
        run: |
          export PATH=/usr/lib/gcc-snapshot/bin:$PATH
          ./tools/ci/travis.sh importdb ragnarok ragnarok ragnarok $SQLHOST

      - name: get plugins
        run: |
          export PATH=/usr/lib/gcc-snapshot/bin:$PATH
          ./tools/ci/travis.sh getplugins || true

      - name: build
        run: |
          export PATH=/usr/lib/gcc-snapshot/bin:$PATH
          ./tools/ci/travis.sh build $CONFIGURE_FLAGS

      - name: test
        run: |
          export PATH=/usr/lib/gcc-snapshot/bin:$PATH
          export LD_PRELOAD=/usr/lib/gcc-snapshot/lib/libasan.so.8.0.0
          ./tools/ci/travis.sh test ragnarok ragnarok ragnarok $SQLHOST

      - name: extra test
        if: env.PACKET_VERSION != '--enable-packetver=20130724'
        run: |
          export PATH=/usr/lib/gcc-snapshot/bin:$PATH
          export LD_PRELOAD=/usr/lib/gcc-snapshot/lib/libasan.so.8.0.0
          ./tools/ci/travis.sh extratest
