name: tools

on: workflow_call

env:
  MYSQL_DATABASE: 'ragnarok'
  MYSQL_USER: 'ragnarok'
  MYSQL_PASSWORD: 'ragnarok'
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  DEBIAN_COMMON_PACKAGES: php php-xml composer wget python3

jobs:
  build:
    runs-on: ubuntu-latest

    # github.head_ref will stop previous runs in the same PR (if in a PR)
    # github.run_id is a fallback when outside a PR (e.g. every merge in master will run, and previous won't stop)
    concurrency:
      group: tools-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    container:
      image: debian:unstable
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: info
        run: |
          uname -a

      - name: install packages
        run: |
          ./tools/ci/retry.sh apt-get update
          ./tools/ci/retry.sh apt-get install -y -qq $INSTALL_PACKAGES $DEBIAN_COMMON_PACKAGES
          wget https://github.com/open-composer/composer/releases/download/2.2.9/composer.phar
          mkdir -p /usr/local/bin
          mv composer.phar /usr/local/bin/composer
          chmod +x /usr/local/bin/composer

      - name: check sql syntax
        run: |
          cd tools/php-sqllint
          ../../tools/ci/retry.sh /usr/local/bin/composer update
          ../../tools/ci/retry.sh /usr/local/bin/composer install --no-interaction --prefer-source
          cd ../..
          ./tools/checksql.sh

          #./tools/ci/retry.sh composer self-update

      - name: check sql updates
        run: |
          ./tools/checksql.py
